import type { Metadata } from "next";
import React from "react";
import { sans } from "@/utils/fonts";
import "./globals.css";

export const metadata: Metadata = {
  title: `Formula 1 ${new Date().getFullYear()}`,
  description: "Generated by create next app",
};

interface Props extends React.PropsWithChildren<{}> {}

export default function RootLayout({
  children,
}: Readonly<Props>) {
  return (
    <html lang="en">
      <body className={sans.variable}>
        {children}
      </body>
    </html>
  );
}
